export const AuthCode = {
  SIGNED_IN: 'SIGNED_IN',
  TOKEN_REFRESHED: 'TOKEN_REFRESHED',
  SIGNED_OUT: 'SIGNED_OUT',
  VERIFICATION_SENT: 'VERIFICATION_SENT',
  PASSWORD_RESET_SENT: 'PASSWORD_RESET_SENT',
  INVALID_GOOGLE_TOKEN: 'INVALID_GOOGLE_TOKEN',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
} as const;
