export const NotificationsCode = {
  NOTIFICATION_SETTINGS_FETCHED: 'NOTIFICATION_SETTINGS_FETCHED',
  NOTIFICATION_SETTINGS_UPDATED: 'NOTIFICATION_SETTINGS_UPDATED',
  PUSH_TOKEN_REGISTERED: 'PUSH_TOKEN_REGISTERED',
  PUSH_TOKEN_REMOVED: 'PUSH_TOKEN_REMOVED',
  INVALID_TIMEZONE: 'INVALID_TIMEZONE',
} as const;
