export const AttachmentsCode = {
  UPLOAD_CREATED: 'UPLOAD_CREATED',
  ATTACHMENT_NOT_FOUND: 'ATTACHMENT_NOT_FOUND',
  ATTACHMENT_NOT_UPLOADED: 'ATTACHMENT_NOT_UPLOADED',
  ATTACHMENT_MISMATCH: 'ATTACHMENT_MISMATCH',
  STORAGE_LIMIT_REACHED: 'STORAGE_LIMIT_REACHED',
} as const;
