export const WarrantyCode = {
  WARRANTIES_FETCHED: 'WARRANTIES_FETCHED',
  WARRANTY_FETCHED: 'WARRANTY_FETCHED',
  WARRANTY_CREATED: 'WARRANTY_CREATED',
  WARRANTY_UPDATED: 'WARRANTY_UPDATED',
  WARRANTY_DELETED: 'WARRANTY_DELETED',
  WARRANTY_NOT_FOUND: 'WARRANTY_NOT_FOUND',
  WARRANTY_LIMIT_REACHED: 'WARRANTY_LIMIT_REACHED',
  EXPIRY_BEFORE_PURCHASE: 'EXPIRY_BEFORE_PURCHASE',
} as const;
