export const UsersCode = {
  USER_FETCHED: 'USER_FETCHED',
  DELETION_CODE_SENT: 'DELETION_CODE_SENT',
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',
  DELETION_CODE_INVALID: 'DELETION_CODE_INVALID',
  DELETION_CODE_EXPIRED: 'DELETION_CODE_EXPIRED',
  DELETION_CODE_RECENTLY_SENT: 'DELETION_CODE_RECENTLY_SENT',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  CODE_INVALID: 'CODE_INVALID',
  CODE_EXPIRED: 'CODE_EXPIRED',
} as const;
